// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dme

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccesCriticalClient is the client API for AccesCritical service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccesCriticalClient interface {
	AttemptAcces(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type accesCriticalClient struct {
	cc grpc.ClientConnInterface
}

func NewAccesCriticalClient(cc grpc.ClientConnInterface) AccesCriticalClient {
	return &accesCriticalClient{cc}
}

func (c *accesCriticalClient) AttemptAcces(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/dme.AccesCritical/attemptAcces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccesCriticalServer is the server API for AccesCritical service.
// All implementations must embed UnimplementedAccesCriticalServer
// for forward compatibility
type AccesCriticalServer interface {
	AttemptAcces(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedAccesCriticalServer()
}

// UnimplementedAccesCriticalServer must be embedded to have forward compatible implementations.
type UnimplementedAccesCriticalServer struct {
}

func (UnimplementedAccesCriticalServer) AttemptAcces(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttemptAcces not implemented")
}
func (UnimplementedAccesCriticalServer) mustEmbedUnimplementedAccesCriticalServer() {}

// UnsafeAccesCriticalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccesCriticalServer will
// result in compilation errors.
type UnsafeAccesCriticalServer interface {
	mustEmbedUnimplementedAccesCriticalServer()
}

func RegisterAccesCriticalServer(s grpc.ServiceRegistrar, srv AccesCriticalServer) {
	s.RegisterService(&AccesCritical_ServiceDesc, srv)
}

func _AccesCritical_AttemptAcces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccesCriticalServer).AttemptAcces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dme.AccesCritical/attemptAcces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccesCriticalServer).AttemptAcces(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AccesCritical_ServiceDesc is the grpc.ServiceDesc for AccesCritical service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccesCritical_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dme.AccesCritical",
	HandlerType: (*AccesCriticalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "attemptAcces",
			Handler:    _AccesCritical_AttemptAcces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
